#pragma once
#include "Component.h"
#include "Transform.h"
#include "Sprite.h"
#include "PhysObject.h"
#include "ColliderPolygon.h"
#include "ColliderBox.h"
#include "ColliderCircle.h"
#include "Player.h"